export const words = [
    { word: "apple", hint: "A common fruit that can be red, green, or yellow." },
    { word: "bicycle", hint: "A vehicle with two wheels, powered by pedaling." },
    { word: "mountain", hint: "A large natural elevation of the earth's surface." },
    { word: "python", hint: "A programming language named after a type of snake." },
    { word: "guitar", hint: "A musical instrument with strings, often used in rock music." },
    { word: "ocean", hint: "A large body of salt water that covers much of the earth's surface." },
    { word: "umbrella", hint: "An item used for protection against rain or sunlight." },
    { word: "elephant", hint: "The largest land animal with a trunk." },
    { word: "football", hint: "A popular sport played with a round or oval ball, depending on the region." },
    { word: "kangaroo", hint: "A marsupial animal known for jumping, found in Australia." },
    { word: "volcano", hint: "A mountain that can erupt with lava." },
    { word: "airplane", hint: "A flying vehicle that transports people across long distances." },
    { word: "camera", hint: "A device used to capture photographs or videos." },
    { word: "computer", hint: "An electronic device used for processing data and performing tasks." },
    { word: "diamond", hint: "A precious stone known for its brilliance and hardness." },
    { word: "sunflower", hint: "A tall plant with a large yellow flower that follows the sun." },
    { word: "jungle", hint: "A dense forest found in tropical regions." },
    { word: "whale", hint: "A large marine mammal, the largest living animal on earth." },
    { word: "piano", hint: "A musical instrument with keys, often used in classical music." },
    { word: "rainbow", hint: "A colorful arc seen in the sky after rain." },
    { word: "photo", hint: "Capturing anything into visual digital memory."},
    { word: "SOCCER", hint: "A game played between two teams of eleven players with a round ball" },
    { word: "BASKETBALL", hint: "A game played between two teams of five players in which goals are scored by throwing a ball through a hoop" },
    { word: "TENNIS", hint: "A racket sport played individually against a single opponent or between two teams of two players each" },
    { word: "BASEBALL", hint: "A bat-and-ball game played between two opposing teams" },
    { word: "CRICKET", hint: "A bat-and-ball game played between two teams of eleven players" },
    { word: "GOLF", hint: "A game in which players use clubs to hit balls into a series of holes on a course" },
    { word: "SWIMMING", hint: "The sport of moving through water by using the arms and legs" },
    { word: "VOLLEYBALL", hint: "A game in which two teams hit a ball over a high net using their hands" },
    { word: "RUGBY", hint: "A team sport that originated in England, similar to football" },
    { word: "GYMNASTICS", hint: "A sport involving exercises and performances on various apparatus" },
    { word: "ATHLETICS", hint: "A collection of sports events that involve competitive running, jumping, throwing, and walking" },
    { word: "HOCKEY", hint: "A game played on ice or a field in which players use sticks to hit a puck or ball" },
    { word: "SKATEBOARDING", hint: "An action sport that involves riding and performing tricks on a skateboard" },
    { word: "MMA", hint: "Mixed martial arts, a full-contact combat sport" },
    { word: "BOXING", hint: "A sport in which two people throw punches at each other for a predetermined amount of time" },
    { word: "FENCING", hint: "A sport in which two competitors fight using swords" },
    { word: "KARATE", hint: "A form of martial art that focuses on striking techniques" },
    { word: "DODGEBALL", hint: "A team sport in which players try to hit opponents with a ball while avoiding being hit" },
    { word: "SNOWBOARDING", hint: "The action sport of riding a snowboard down snow-covered hills" },
    { word: "LACROSSE", hint: "A team sport played with a stick and ball" },
    { word: "WRESTLING", hint: "A combat sport involving grappling techniques" },
    { word: "CONTINENT", hint: "One of the main landmasses of the earth" },
    { word: "ISLAND", hint: "A piece of land surrounded by water" },
    { word: "MOUNTAIN", hint: "A large natural elevation of the earth's surface" },
    { word: "RIVER", hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another river" },
    { word: "DESERT", hint: "A barren area of land where little precipitation occurs" },
    { word: "PLATEAU", hint: "An area of relatively level high ground" },
    { word: "OCEAN", hint: "A vast body of salt water that covers almost three-quarters of the earth's surface" },
    { word: "GLACIER", hint: "A slowly moving mass of ice" },
    { word: "VOLCANO", hint: "An opening in the earth's crust through which lava, ash, and gases erupt" },
    { word: "FOREST", hint: "A large area covered chiefly with trees and undergrowth" },
    { word: "ATMOSPHERE", hint: "The envelope of gases surrounding the earth" },
    { word: "CANYON", hint: "A deep gorge, typically one with a river flowing through it" },
    { word: "FJORD", hint: "A long, deep, narrow body of water between high cliffs" },
    { word: "ARCHIPELAGO", hint: "A group of islands" },
    { word: "TUNDRA", hint: "A large, flat, treeless Arctic region" },
    { word: "SAVANNAH", hint: "A grassy plain in tropical and subtropical regions" },
    { word: "BAY", hint: "A broad inlet of the sea where the land curves inward" },
    { word: "MARSH", hint: "An area of low-lying land that is flooded in wet seasons" },
    { word: "HIGHLAND", hint: "An area of high or mountainous land" },
    { word: "PENINSULA", hint: "A piece of land almost surrounded by water" },
    { word: "CAPITAL", hint: "The city where a government's central offices are located" },
    { word: "GUITAR", hint: "A string instrument played with fingers or a pick" },
    { word: "PIANO", hint: "A large musical instrument with keys" },
    { word: "DRUM", hint: "A percussion instrument played by striking with sticks" },
    { word: "SINGER", hint: "A person who performs music with their voice" },
    { word: "BAND", hint: "A group of musicians who play together" },
    { word: "ALBUM", hint: "A collection of songs released together" },
    { word: "SONG", hint: "A short piece of music with lyrics" },
    { word: "CHORUS", hint: "A repeated section of a song" },
    { word: "MELODY", hint: "A sequence of notes that is musically satisfying" },
    { word: "SYMPHONY", hint: "A lengthy orchestral composition" },
    { word: "HARMONY", hint: "The combination of simultaneously sounded musical notes" },
    { word: "LYRICS", hint: "The words of a song" },
    { word: "CONCERT", hint: "A live music performance" },
    { word: "NOTES", hint: "Symbols representing musical sounds" },
    { word: "JAZZ", hint: "A genre of music characterized by improvisation" },
    { word: "CLASSICAL", hint: "A genre of music known for its complex structure" },
    { word: "FOLK", hint: "Music that originates from traditional cultural expressions" },
    { word: "RHYTHM", hint: "A strong, regular repeated pattern of movement or sound" },
    { word: "TUNES", hint: "A series of musical notes that are pleasing to hear" },
    { word: "SCALES", hint: "A series of musical notes in ascending or descending order" },
    { word: "VOCAL", hint: "Related to the human voice" },
    { word: "CONTINENT", hint: "Large landmass like Asia or Africa" },
    { word: "RIVER", hint: "A large natural stream of water flowing in a channel" },
    { word: "MOUNTAIN", hint: "A large elevation of the earth's surface" },
    { word: "PLATEAU", hint: "A flat, elevated area of land" },
    { word: "ISLAND", hint: "A piece of land surrounded by water" },
    { word: "OCEAN", hint: "A vast body of saltwater covering most of the Earth's surface" },
    { word: "DESERT", hint: "A barren area of land with little rainfall" },
    { word: "GLACIER", hint: "A slow-moving mass of ice" },
    { word: "ECOSYSTEM", hint: "A community of living organisms and their environment" },
    { word: "CANYON", hint: "A deep gorge, typically one with a river flowing through it" },
    { word: "PLAIN", hint: "A large area of flat land" },
    { word: "HILLS", hint: "Raised areas of land that are lower than mountains" },
    { word: "TUNDRA", hint: "A flat, treeless Arctic region" },
    { word: "VOLCANO", hint: "An opening in the Earth's crust that erupts lava" },
    { word: "ATMOSPHERE", hint: "The layer of gases surrounding Earth" },
    { word: "ARCHIPELAGO", hint: "A group of islands" },
    { word: "MARSH", hint: "Wetland dominated by herbaceous plants" },
    { word: "FJORD", hint: "A narrow inlet of the sea between cliffs" },
    { word: "BAY", hint: "A body of water partially surrounded by land" },
    { word: "CAPITAL", hint: "The city where a country's government is located" },
    { word: "NIPA", hint: "McDonalds' best employee!"},
    { word: "Aleksi", hint: "Boss :sunglasses:"},
    { word: "REVOLUTION", hint: "A forcible overthrow of a government or social order" },
    { word: "EMPIRE", hint: "A group of states or countries under a single ruler" },
    { word: "RENAISSANCE", hint: "The cultural rebirth in Europe during the 14th-17th centuries" },
    { word: "PHARAOH", hint: "A ruler in ancient Egypt" },
    { word: "COLONY", hint: "A territory settled and controlled by another country" },
    { word: "MEDIEVAL", hint: "Relating to the Middle Ages" },
    { word: "DEMOCRACY", hint: "A system of government by the whole population" },
    { word: "INDEPENDENCE", hint: "The state of being free from outside control" },
    { word: "ARMISTICE", hint: "An agreement made by opposing sides in a war to stop fighting" },
    { word: "CRUSADE", hint: "A series of religious wars in the medieval period" },
    { word: "PYRAMID", hint: "A monumental structure in ancient Egypt" },
    { word: "DICTATOR", hint: "A ruler with total power over a country" },
    { word: "CIVILIZATION", hint: "The stage of human social and cultural development" },
    { word: "DYNASTY", hint: "A line of hereditary rulers of a country" },
    { word: "FEUDALISM", hint: "A social system in medieval Europe" },
    { word: "MONARCHY", hint: "A form of government with a monarch at the head" },
    { word: "TREATY", hint: "A formal agreement between countries" },
    { word: "SLAVERY", hint: "The practice of owning people as property" },
    { word: "REVIVAL", hint: "An improvement in the condition or strength of something" },
    { word: "WARFARE", hint: "Engagement in or the activities involved in war" },
    { word: "JURISDICTION", hint: "The official power to make legal decisions and judgments" },
    { word: "STAREDECISIS", hint: "The legal principle of determining points in litigation according to precedent" },
    { word: "HABEASCORPUS", hint: "A legal writ demanding a person be brought before a judge" },
    { word: "TORT", hint: "A civil wrong causing harm or loss to an individual" },
    { word: "INJUNCTION", hint: "A judicial order that restrains a person from starting or continuing an action" },
    { word: "SUBPOENA", hint: "A writ ordering a person to attend a court" },
    { word: "ARBITRATION", hint: "The use of an arbitrator to settle a dispute" },
    { word: "LITIGATION", hint: "The process of taking legal action" },
    { word: "CONSTITUTION", hint: "A body of fundamental principles according to which a state is governed" },
    { word: "EXTRADITION", hint: "The action of handing over a person accused or convicted of a crime to another jurisdiction" },
    { word: "PLAINTIFF", hint: "A person who brings a case against another in a court of law" },
    { word: "DEFAMATION", hint: "The act of damaging someone's good reputation" },
    { word: "ASSAULT", hint: "A physical attack" },
    { word: "AFFIDAVIT", hint: "A written statement confirmed by oath for use as evidence in court" },
    { word: "JURISPRUDENCE", hint: "The theory or philosophy of law" },
    { word: "LIABILITY", hint: "The state of being legally responsible for something" },
    { word: "NEGLIGENCE", hint: "Failure to take proper care in doing something legally required" },
    { word: "BAILMENT", hint: "The process of placing property in the custody of another" },
    { word: "REMAND", hint: "To send a case back to a lower court for further action" },
    { word: "INDICTMENT", hint: "A formal charge or accusation of a serious crime" },
    { word: "LINCOLN", hint: "16th President of the United States during the Civil War" },
    { word: "CHURCHILL", hint: "British Prime Minister during World War II" },
    { word: "MANDELA", hint: "Anti-apartheid revolutionary and former President of South Africa" },
    { word: "WASHINGTON", hint: "First President of the United States" },
    { word: "GANDHI", hint: "Leader of the Indian independence movement against British rule" },
    { word: "THATCHER", hint: "First female Prime Minister of the United Kingdom" },
    { word: "CASTRO", hint: "Cuban revolutionary and politician who served as Prime Minister and President" },
    { word: "KENNEDY", hint: "35th President of the United States, assassinated in 1963" },
    { word: "STALIN", hint: "Leader of the Soviet Union from the mid-1920s until his death" },
    { word: "ROOSEVELT", hint: "32nd President of the United States, led the country during the Great Depression and WWII" },
    { word: "HITLER", hint: "Dictator of Nazi Germany during World War II" },
    { word: "OBAMA", hint: "44th President of the United States, first African-American to hold the office" },
    { word: "TRUDEAU", hint: "Prime Minister of Canada, known for progressive policies" },
    { word: "MACRON", hint: "President of France, elected in 2017" },
    { word: "POTTERING", hint: "German politician, served as President of the European Parliament" },
    { word: "MERKEL", hint: "First female Chancellor of Germany" },
    { word: "PUTIN", hint: "Current President of Russia, in power since 1999" },
    { word: "TRUMP", hint: "45th President of the United States, known for his real estate and business background" },
    { word: "JOHNSON", hint: "Former British Prime Minister, key figure in Brexit" },
    { word: "SANCHEZ", hint: "Prime Minister of Spain, leader of the Spanish Socialist Workers' Party" },
    { word: "TRUMP", hint: "President that has worked at McDonalds"},
    { word: "QUIXOTIC", hint: "Extremely idealistic, unrealistic, and impractical" },
    { word: "LUGUBRIOUS", hint: "Looking or sounding sad and dismal" },
    { word: "OBFUSCATE", hint: "To deliberately make something unclear or difficult to understand" },
    { word: "SYCOPHANT", hint: "A person who flatters someone important to gain advantage" },
    { word: "PERSPICACIOUS", hint: "Having a ready insight into and understanding of things" },
    { word: "INEFFABLE", hint: "Too great or extreme to be expressed in words" },
    { word: "MELLIFLUOUS", hint: "Pleasantly smooth and musical to hear" },
    { word: "SOLIPSISM", hint: "The view or theory that only the self is sure to exist" },
    { word: "SESQUIPEDALIAN", hint: "A person who uses long words" },
    { word: "LACONIC", hint: "Using very few words" },
    { word: "INTRANSIGENT", hint: "Unwilling to change one's views or to agree" },
    { word: "MENDACIOUS", hint: "Not telling the truth, lying" },
    { word: "PERFIDIOUS", hint: "Deceitful and untrustworthy" },
    { word: "PUSILLANIMOUS", hint: "Showing a lack of courage or determination" },
    { word: "TACITURN", hint: "Reserved or uncommunicative in speech" },
    { word: "SURREPTITIOUS", hint: "Kept secret, especially because it would not be approved of" },
    { word: "PENURIOUS", hint: "Extremely poor, poverty-stricken" },
    { word: "VERISIMILITUDE", hint: "The appearance of being true or real" },
    { word: "ANTIDISESTABLISHMENTARIANISM", hint: "Opposition to the withdrawal of state support from an established church" },
    { word: "TRISKAIDEKAPHOBIA", hint: "Fear or avoidance of the number 13" },
    { word: "DISCOMBOBULATE", hint: "To confuse or disconcert; upset" },
    { word: "KAKORRHAPHIOPHOBIA", hint: "Fear of failure" },
    { word: "EQUANIMITY", hint: "Mental calmness, composure, and evenness of temper" },
    { word: "ALACRITY", hint: "Brisk and cheerful readiness" },
    { word: "ENERVATE", hint: "To cause someone to feel drained of energy" },
    { word: "BELLICOSE", hint: "Demonstrating aggression and willingness to fight" },
    { word: "EXECRABLE", hint: "Extremely bad or unpleasant" },
    { word: "PULCHRITUDE", hint: "Physical beauty" },
    { word: "FARRAGO", hint: "A confused mixture" },
    { word: "CIRCUMLOCUTION", hint: "The use of many words where fewer would do" },
    { word: "BOMBASTIC", hint: "High-sounding but with little meaning; inflated" },
    { word: "TUMULTUOUS", hint: "Excited, confused, or disorderly" },
    { word: "ONOMATOPOEIA", hint: "The formation of a word from a sound associated with what is named" },
    { word: "INSOUCIANT", hint: "Showing a casual lack of concern; indifferent" },
    { word: "PANTHEON", hint: "All the gods of a people or religion collectively" },
    { word: "CONFLAGRATION", hint: "A large, destructive fire" },
    { word: "PLUTOCRACY", hint: "Government by the wealthy" },
    { word: "CACHINNATE", hint: "To laugh loudly or immoderately" },
    { word: "JUXTAPOSITION", hint: "The fact of two things being seen or placed close together with contrasting effect" },
    { word: "PREVARICATE", hint: "To speak or act in an evasive way" },
    { word: "OSTRACIZE", hint: "To exclude someone from a society or group" },
    { word: "SERENDIPITY", hint: "The occurrence of events by chance in a happy or beneficial way" },
    { word: "OBSEQUIOUS", hint: "Obedient or attentive to an excessive degree" },
    { word: "RECALCITRANT", hint: "Having an obstinately uncooperative attitude towards authority" },
    { word: "NEFARIOUS", hint: "Wicked or criminal" },
    { word: "PROCLIVITY", hint: "A tendency to choose or do something regularly" },
    { word: "SPLENETIC", hint: "Bad-tempered; spiteful" },
    { word: "INDOLENT", hint: "Wanting to avoid activity or exertion; lazy" },
    { word: "OBDURATE", hint: "Stubbornly refusing to change one's opinion or course of action" },
    { word: "ANACHRONISTIC", hint: "Belonging to a period other than that being portrayed" }
  ];
  
  